"""empty message

Revision ID: 2e3197e40543
Revises: 051c561bee8a
Create Date: 2019-12-14 18:06:54.622601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3197e40543'
down_revision = '051c561bee8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('address', sa.String(), nullable=True))
    op.add_column('employee_table', sa.Column('password', sa.String(), nullable=True))
    op.add_column('employee_table', sa.Column('pincode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employee_table_employee_id'), 'employee_table', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_table_employee_id'), table_name='employee_table')
    op.drop_column('employee_table', 'pincode')
    op.drop_column('employee_table', 'password')
    op.drop_column('employee_table', 'address')
    # ### end Alembic commands ###
