"""empty message

Revision ID: 7d7bdd14a597
Revises: 217d09610948
Create Date: 2019-12-15 18:59:45.422338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7bdd14a597'
down_revision = '217d09610948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_info', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('device_info', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_info', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('device_info', 'is_deleted')
    # ### end Alembic commands ###
