"""empty message

Revision ID: 9e2abdf1fcdf
Revises: 2e3197e40543
Create Date: 2019-12-15 09:14:18.112584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2abdf1fcdf'
down_revision = '2e3197e40543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_table', 'is_active')
    # ### end Alembic commands ###
