"""empty message

Revision ID: f5a88134ca43
Revises: cd2a5f56eff2
Create Date: 2019-12-15 13:28:53.289015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a88134ca43'
down_revision = 'cd2a5f56eff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_info', sa.Column('device_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'device_info', ['device_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_info', type_='unique')
    op.drop_column('device_info', 'device_id')
    # ### end Alembic commands ###
