"""empty message

Revision ID: fe866ff6f94b
Revises: 9e2abdf1fcdf
Create Date: 2019-12-15 09:30:15.674752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe866ff6f94b'
down_revision = '9e2abdf1fcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('is_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_table', 'is_manager')
    # ### end Alembic commands ###
